const washbtn = document.getElementById("wash-btn")
const mowbtn = document.getElementById("mow-btn")
const pullbtn = document.getElementById("pull-btn")
let additem = document.getElementById("additem")
let addprice = document.getElementById("addprice")
let totalAmount = document.getElementById("total-amt")
const resetBtn = document.getElementById("reset-btn")
